import Head from "next/head";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className="flex justify-between w-full p-5  text-sm text-gray-700 ">
        {/* left section */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* right section */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Image</p>

          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 hover:bg-gray-100 rounded-full cursor-pointer" />

          {/* Avatar */}
          {/* creating own avatar component */}
          <Avatar />
        </div>
      </header>

      {/* Body */}

      {/* Footer */}
    </div>
  );
}
